### PR TITLE
Changes ref from 2018 to 2025 at 09-queues-challenge

### PR DESCRIPTION
**Pull request by lamtrinhdev**
Changes ref from 2018 to 2025 at 09-queues-challenge

### CODE REVIEW

**Comment by lamtrinhdev** [comment]
Dear @kelvinlauKL ,

I have a minor update for changing ref from 2018 to 2025 at 09-queues-challenge. Could you please help me to review it?

Thanks,
Lam

**Comment by svanimpe** [comment]
@lamtrinhdev 

Thanks for these PRs.
The book is being updated as we speak, and these changes will be in the next edition (for all chapters).

**Comment by lamtrinhdev** [comment]
Dear @svanimpe ,

Thank you for your feedback. I am clear now. I see Kelvin updated all from 2021 to 2025. I just found some missed (2018), I created the PR to merged to Kelvin branch that just make sure we will not miss that.

Thanks,
Lam

**Review by kelvinlauKL — APPROVED** [review]
Thanks Lam!

**Pull request merged**
